services:
  oeb-nuxt-prod:
    image: dbruechner/openebench-nuxt-prod
    restart: always
    ports:
      - 4000:80
  oeb-nuxt-dev:
    image: dbruechner/openebench-nuxt-dev
    restart: always
    ports:
      - 4001:80
  oeb-nuxt-dev2:
    image: dbruechner/openebench-nuxt-dev2
    restart: always
    ports:
      - 4002:80
