export default [
	{
		_id: 'OEBE0020000000',
		dates: { creation: '2011-07-07T00:00:00Z', __typename: 'BDates' },
		name: 'Quest for Orthologs - 2011 Reference Proteomes',
		url: 'http://genome.crg.es/~tgabaldon/QfO4/index.html',
		challenges: [
			{
				_id: 'OEBX0020000005',
				name: 'Generalized Species Tree Discordance in Fungi benchmark',
				acronym: 'G_STD_Fungi',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX0020000003',
				name: 'Gene Ontology Conservation Test benchmark',
				acronym: 'GOtest',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX0020000007',
				name: 'Generalized Species Tree Discordance in LUCA benchmark',
				acronym: 'G_STD_LUCA',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX0020000002',
				name: 'Species Tree Discordance in Eukaryota benchmark',
				acronym: 'STD_Eukaryota',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX0020000006',
				name: 'Generalized Species Tree Discordance in Eukaryota benchmark',
				acronym: 'G_STD_Eukaryota',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX0020000004',
				name: 'Agreement with Reference Gene Phylogenies: TreeFam-A benchmark',
				acronym: 'TreeFam-A',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX0020000009',
				name: 'Enzyme Classification Conservation Test benchmark',
				acronym: 'ECtest',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX0020000000',
				name: 'Agreement with Reference Gene Phylogenies: SwissTree benchmark',
				acronym: 'SwissTree',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX0020000001',
				name: 'Species Tree Discordance in Fungi benchmark',
				acronym: 'STD_Fungi',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX0020000008',
				name: 'Generalized Species Tree Discordance in Vertebrata benchmark',
				acronym: 'G_STD_Vertebrata',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
		],
		__typename: 'BenchmarkingEvent',
	},
	{
		_id: 'OEBE0020000002',
		dates: { creation: '2020-11-04T00:00:00Z', __typename: 'BDates' },
		name: 'Quest for Orthologs - 2020 Reference Proteomes',
		url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl',
		challenges: [
			{
				_id: 'OEBX0020000013',
				name: 'Agreement with Reference Gene Phylogenies: TreeFam-A benchmark',
				acronym: 'TreeFam-A',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX002000000U',
				name: 'Generalized Species Tree Discordance in Vertebrata benchmark',
				acronym: 'G_STD2_Vertebrata',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX0020000012',
				name: 'Agreement with Reference Gene Phylogenies: SwissTree benchmark',
				acronym: 'SwissTree',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX002000000T',
				name: 'Generalized Species Tree Discordance in Luca benchmark',
				acronym: 'G_STD2_Luca',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX002000000S',
				name: 'Generalized Species Tree Discordance in Fungi benchmark',
				acronym: 'G_STD2_Fungi',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX002000000Q',
				name: 'Gene Ontology Conservation Test benchmark',
				acronym: 'GOtest',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX002000000Z',
				name: 'Species Tree Discordance in Bacteria benchmark',
				acronym: 'STD_Bacteria',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX0020000011',
				name: 'Species Tree Discordance in Fungi benchmark',
				acronym: 'STD_Fungi',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX0020000010',
				name: 'Species Tree Discordance in Eukaryota benchmark',
				acronym: 'STD_Eukaryota',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX002000000R',
				name: 'Generalized Species Tree Discordance in Eukaryota benchmark',
				acronym: 'G_STD2_Eukaryota',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX002000000P',
				name: 'Enzyme Classification Conservation Test benchmark',
				acronym: 'ECtest',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX0020000014',
				name: 'Agreement with Reference Gene Phylogenies: VGNC benchmark',
				acronym: 'VGNC',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
		],
		__typename: 'BenchmarkingEvent',
	},
	{
		_id: 'OEBE0020000001',
		dates: { creation: '2018-07-07T00:00:00Z', __typename: 'BDates' },
		name: 'Quest for Orthologs - 2018 Reference Proteomes',
		url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl',
		challenges: [
			{
				_id: 'OEBX002000000B',
				name: 'Gene Ontology Conservation Test benchmark',
				acronym: 'GOtest',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX002000000J',
				name: 'Generalized Species Tree Discordance in Vertebrata benchmark',
				acronym: 'G_STD_Vertebrata',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX002000000L',
				name: 'Species Tree Discordance in Fungi benchmark',
				acronym: 'STD_Fungi',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX002000000G',
				name: 'Generalized Species Tree Discordance in Eukaryota benchmark',
				acronym: 'G_STD_Eukaryota',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX002000000N',
				name: 'Agreement with Reference Gene Phylogenies: TreeFam-A benchmark',
				acronym: 'TreeFam-A',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX002000000F',
				name: 'Generalized Species Tree Discordance in Vertebrata benchmark',
				acronym: 'G_STD2_Vertebrata',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX002000000D',
				name: 'Generalized Species Tree Discordance in Fungi benchmark',
				acronym: 'G_STD2_Fungi',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX002000000O',
				name: 'Species Tree Discordance in Bacteria benchmark',
				acronym: 'STD_Bacteria',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX002000000C',
				name: 'Generalized Species Tree Discordance in Eukaryota benchmark',
				acronym: 'G_STD2_Eukaryota',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX002000000A',
				name: 'Enzyme Classification Conservation Test benchmark',
				acronym: 'ECtest',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX002000000E',
				name: 'Generalized Species Tree Discordance in LUCA benchmark',
				acronym: 'G_STD2_LUCA',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX002000000K',
				name: 'Species Tree Discordance in Eukaryota benchmark',
				acronym: 'STD_Eukaryota',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX002000000I',
				name: 'Generalized Species Tree Discordance in LUCA benchmark',
				acronym: 'G_STD_LUCA',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX002000000M',
				name: 'Agreement with Reference Gene Phylogenies: SwissTree benchmark',
				acronym: 'SwissTree',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
			{
				_id: 'OEBX002000000H',
				name: 'Generalized Species Tree Discordance in Fungi benchmark',
				acronym: 'G_STD_Fungi',
				url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
				__typename: 'Challenge',
			},
		],
		__typename: 'BenchmarkingEvent',
	},
];
