export default {
	_id: 'OEBE0020000000',
	dates: { creation: '2011-07-07T00:00:00Z', __typename: 'BDates' },
	name: 'Quest for Orthologs - 2011 Reference Proteomes',
	url: 'http://genome.crg.es/~tgabaldon/QfO4/index.html',
	challenges: [
		{
			_id: 'OEBX0020000005',
			name: 'Generalized Species Tree Discordance in Fungi benchmark',
			acronym: 'G_STD_Fungi',
			url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
			__typename: 'Challenge',
		},
		{
			_id: 'OEBX0020000003',
			name: 'Gene Ontology Conservation Test benchmark',
			acronym: 'GOtest',
			url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
			__typename: 'Challenge',
		},
		{
			_id: 'OEBX0020000007',
			name: 'Generalized Species Tree Discordance in LUCA benchmark',
			acronym: 'G_STD_LUCA',
			url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
			__typename: 'Challenge',
		},
		{
			_id: 'OEBX0020000002',
			name: 'Species Tree Discordance in Eukaryota benchmark',
			acronym: 'STD_Eukaryota',
			url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
			__typename: 'Challenge',
		},
		{
			_id: 'OEBX0020000006',
			name: 'Generalized Species Tree Discordance in Eukaryota benchmark',
			acronym: 'G_STD_Eukaryota',
			url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
			__typename: 'Challenge',
		},
		{
			_id: 'OEBX0020000004',
			name: 'Agreement with Reference Gene Phylogenies: TreeFam-A benchmark',
			acronym: 'TreeFam-A',
			url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
			__typename: 'Challenge',
		},
		{
			_id: 'OEBX0020000009',
			name: 'Enzyme Classification Conservation Test benchmark',
			acronym: 'ECtest',
			url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
			__typename: 'Challenge',
		},
		{
			_id: 'OEBX0020000000',
			name: 'Agreement with Reference Gene Phylogenies: SwissTree benchmark',
			acronym: 'SwissTree',
			url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
			__typename: 'Challenge',
		},
		{
			_id: 'OEBX0020000001',
			name: 'Species Tree Discordance in Fungi benchmark',
			acronym: 'STD_Fungi',
			url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
			__typename: 'Challenge',
		},
		{
			_id: 'OEBX0020000008',
			name: 'Generalized Species Tree Discordance in Vertebrata benchmark',
			acronym: 'G_STD_Vertebrata',
			url: 'https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2',
			__typename: 'Challenge',
		},
	],
	__typename: 'BenchmarkingEvent',
};
