<template>
	<v-card outlined elevation="2" class="pr-8 pb-6">
		<!-- Options Button -->
		<PlotWOptions class="copy-icon" :items="dialogItems" />

		<!-- Header -->
		<v-row class="mb-0 pb-0" justify="center">
			<v-col md="11" lg="11" sm="10" xs="12" class="ml-8 mt-5 mb-pd-0">
				<h6 class="text-center mt-6 mb-2">Data formats</h6>

				<v-row class="mt-4" align="stretch">
					<!-- Description -->
					<v-col cols="12" lg="9">
						<p
							style="line-height: 1.8"
							class="card-content-vs text-sm text-gray-700"
						>
							The file formats supported or generated by a software tool define
							how it exchanges data with other tools and systems. Understanding
							format support is essential for assessing software
							<span class="highlight">Interoperability</span> and
							<span class="highlight">Reusability</span>—two key principles of
							FAIR.
						</p>
						<p
							style="line-height: 1.8"
							class="card-content-vs text-sm text-gray-700 mt-2"
						>
							Formats also offer insight into domain conventions, data
							standards, and the potential for integration into Open Science
							workflows across the Life Sciences.
						</p>
					</v-col>

					<!-- Percentage card -->
					<v-col cols="12" lg="3" class="d-flex">
						<v-skeleton-loader
							v-if="isFormatsCountLoading"
							class="flex-grow-1"
							type="card"
						/>
						<div
							v-else
							class="formats-percentage-card d-flex flex-column justify-center align-center text-center"
						>
							<span class="formats-percentage mb-1">
								{{ percentage.toFixed(1) }}%
							</span>
							<p class="font-weight-light mb-0">
								of software use standard
								<span class="font-weight-bold">data formats</span>
							</p>
						</div>
					</v-col>
				</v-row>
			</v-col>
		</v-row>

		<!-- Two plots row -->
		<v-row class="mt-0 pt-0" justify="space-around" align="start">
			<!-- Input formats -->
			<v-col cols="12" md="6">
				<v-skeleton-loader
					v-if="isInputFormatsLoading"
					class="mb-5 ml-10 mr-10"
					type="card"
				/>
				<div v-else>
					<FormatsPlot
						v-if="checkData"
						:data="inputFormatsPlotData"
						color="#F7B55E"
					/>

					<p class="mt-2 text-center mb-2 ml-8">
						<span
							class="text-sm highlight"
							v-if="currentCollection === 'tools'"
						>
							Input formats most frequently supported by tools in the Life
							Sciences, showing common standards.
						</span>
						<span class="text-sm highlight" v-else>
							Input formats most frequently supported by tools in
							{{ currentCollection }}, showing common standards.
						</span>
					</p>
				</div>
			</v-col>

			<!-- Output formats -->
			<v-col cols="12" md="6">
				<v-skeleton-loader
					v-if="isOutputFormatsLoading"
					class="mb-5 ml-10 mr-10"
					type="card"
				/>
				<div v-else>
					<FormatsPlot
						v-if="checkData"
						:data="outputFormatsPlotData"
						color="#6FAD6F"
					/>

					<p class="mt-2 text-center mb-2 ml-8">
						<span
							class="text-sm highlight"
							v-if="currentCollection === 'tools'"
						>
							Output formats most frequently supported by tools in the Life
							Sciences, showing common standards.
						</span>
						<span class="text-sm highlight" v-else>
							Output formats most frequently supported by tools in
							{{ currentCollection }}, showing common standards.
						</span>
					</p>
				</div>
			</v-col>
		</v-row>
	</v-card>
</template>

<script>
import { mapGetters } from 'vuex';
import FormatsPlot from './FormatsPlot.vue';
import PlotWOptions from '~/components/observatory/PlotWOptions.vue';
import { embedCodes } from '~/components/observatory/visualizations/embedCodes.js';

export default {
	name: 'FormatsMain',
	components: {
		FormatsPlot,
		PlotWOptions,
	},
	data() {
		return {
			// NOTE: your v3 has embedCodes.dependencies (copy/paste). For formats it should be embedCodes.formats.
			dialogItems: [embedCodes.inputFormats, embedCodes.outputFormats],
		};
	},
	computed: {
		...mapGetters('observatory/trends', {
			inputFormats: 'InputFormats',
			outputFormats: 'OutputFormats',
			formatsCount: 'FormatsCount',
			loaded: 'Loaded',
		}),

		// Read collection from v2 root store (same source used in actions)
		currentCollection() {
			return this.$store.state.observatory._currentCollection;
		},

		isInputFormatsLoading() {
			return this.loaded?.inputFormats === true;
		},
		isOutputFormatsLoading() {
			return this.loaded?.outputFormats === true;
		},
		isFormatsCountLoading() {
			return this.loaded?.formatsCount === true;
		},

		percentage() {
			const pct = this.formatsCount?.percentage;
			if (typeof pct !== 'number') return 0;
			return pct * 100;
		},

		// v3 uses trends.InputFormats.data and trends.OutputFormats.data
		inputFormatsPlotData() {
			if (!this.inputFormats) return {};
			return this.inputFormats.data
				? this.inputFormats.data
				: this.inputFormats;
		},
		outputFormatsPlotData() {
			if (!this.outputFormats) return {};
			return this.outputFormats.data
				? this.outputFormats.data
				: this.outputFormats;
		},

		checkData() {
			// Require at least one of them to have keys
			const a = this.inputFormatsPlotData;
			const b = this.outputFormatsPlotData;

			const aOk = a && typeof a === 'object' && Object.keys(a).length > 0;
			const bOk = b && typeof b === 'object' && Object.keys(b).length > 0;

			return aOk || bOk;
		},
	},

	mounted() {
		// Trigger loads like v3 onMounted
		this.$store.dispatch('observatory/trends/getInputFormats');
		this.$store.dispatch('observatory/trends/getOutputFormats');
		this.$store.dispatch('observatory/trends/getFormatsCount');
	},
};
</script>

<style scoped>
.highlight {
	color: #001752f8;
	font-weight: 500;
}

.copy-icon {
	position: absolute;
	top: 5px;
	right: 10px;
}

.card-content-vs {
	font-size: 0.9em !important;
	width: 95%;
	margin: auto;
}

/* Percentage card styling similar to indigo-50 */
.formats-percentage-card {
	width: 100%;
	background: #eef2ff; /* light indigo-ish */
	border-radius: 6px;
	padding: 14px;
	font-size: 1.2em;
}

.formats-percentage {
	font-size: 2.4em;
	line-height: 1;
}
</style>
