export const inputData = {
	x: [
		'Workflow format',
		'FASTG',
		'Article format',
		'PDB',
		'AGP',
		'EMBL-like (text)',
		'SVG',
		'SBML',
		'ISA-TAB',
		'JPG',
		'Sequence features (repeats) format',
		'affymetrix',
		'Binary format',
		'Biological pathway or network format',
		'Sequence range format',
		'FASTQ-solexa',
		'PED',
		'Graph format',
		'FASTA search results format',
		'Gene expression report format',
		'BLAST results',
		'GIF',
		'phyloXML',
		'mzIdentML',
		'Loom',
		'Sequence profile format',
		'Protein structure report (quality evaluation) format',
		'unambiguous pure dna',
		'unambiguous pure rna sequence',
		'Chemical formula format',
		'GVF',
		'RDF format',
		'mhd',
		'qualillumina',
		'CopasiML',
		'Alignment format (XML)',
		'SED-ML',
		'FASTQ',
		'PHYLIP format',
		'psd',
		'qcML',
		'pepXML',
		'ClustalW format',
		'2bit',
		'bed12',
		'Map',
		'PSI MI TAB (MITAB)',
		'EXP',
		'BED',
		'BMP',
		'CHAIN',
		'HMMER format',
		'nbrf/pir',
		'CSV',
		'Alignment format (text)',
		'R file format',
		'GFA 1',
		'pkl',
		'Nucleic acid features (primers) format',
		'AMBER top',
		'Thermo RAW',
		'MAGE-TAB',
		'Biological pathway or network report format',
		'bed6',
		'ENCODE narrow peak format',
		'Ontology format',
		'cel',
		'BLAST XML results format',
		'WIFF format',
		'GFF3-seq',
		'HTML',
		'mzXML',
		'protXML',
		'nexus-seq',
		'FASTQ-illumina',
		'PRIDE XML',
		'mdcrd',
		'BLC',
		'FASTA-like (text)',
		'pgm',
		'LAV',
		'PSI-PAR',
		'HDF',
		'Vienna local RNA secondary structure format',
		'BAM',
		'FASTQ-like format (text)',
		'GFF2',
		'Phylip distance matrix',
		'CRAM',
		'PED/MAP',
		'Phylogenetic tree format (XML)',
		'GFF2-seq',
		'ppm',
		'MAP',
		'pbm',
		'PNG',
		'ibd',
		'GCG MSF',
		'xls',
		'MTX',
		'Raw sequence format',
		'bigBed',
		'Turtle',
		'netCDF',
		'MPEG-4',
		'mmCIF',
		'SCF',
		'Sequence annotation track format',
		'TraML',
		'Experiment annotation format',
		'XYZ',
		'Python script',
		'FASTQ-sanger',
		'GFF',
		'NET',
		'JSON',
		'NeXML',
		'Mascot .dat file',
		'GenBank format',
		'xlsx',
		'mzTab',
		'GZIP format',
		'MAGE-ML',
		'FASTA-like',
		'ABI',
		'BAI',
		'XTC',
		'AB1',
		'imzML metadata file',
		'Text',
		'R script',
		'TSV',
		'PSI MI XML (MIF)',
		'YAML',
		'arff',
		'selex',
		'Sequence-MEME profile alignment',
		'Trajectory format',
		'uniprotkb-like format',
		'mzQuantML',
		'EPS',
		'SAM',
		'pure dna',
		'OBO format',
		'UniProt-like (text)',
		'Taxonomy',
		'dat',
		'MSF',
		'BioYAML',
		'DSV',
		'Phylip tree format',
		'Alignment format',
		'mega',
		'FASTA',
		'Protein interaction format',
		'TIFF',
		'ZIP format',
		'MAT',
		'pir',
		'Mol2',
		'SMILES',
		'Biodiversity data format',
		'SEQUEST .out file',
		'Phylip discrete states format',
		'Hidden Markov model format',
		'N-Triples',
		'BioJSON (Jalview)',
		'proBED',
		'unambiguous pure nucleotide',
		'Matrix format',
		'TNG',
		'Dot-bracket format',
		'SQL',
		'BIOM format',
		'bgzip',
		'HDF5',
		'GROMACS top',
		'Textual format',
		'Phylip format variant',
		'rna',
		'BioPAX',
		'Waters RAW',
		'MAF',
		'axt',
		'sif',
		'SFF',
		'mzML',
		'pure nucleotide',
		'Mass spectrometry data format',
		'HMMER profile alignment (HMM versus sequences)',
		'Image format',
		'consensusXML',
		'SQLite format',
		'dbid',
		'qual',
		'WIG',
		'GCG',
		'trr',
		'Sequence motif format',
		'genePred',
		'X!Tandem XML',
		'SeqXML',
		'XMFA',
		'qual454',
		'mzData',
		'Cytoscape input file format',
		'GTrack',
		'unambiguous pure protein',
		'Sequence feature table format',
		'GFF3',
		'CellML',
		'Sequence feature table format (text)',
		'Tertiary structure format',
		'tabix',
		'VCF',
		'Pearson format',
		'Sequence variation annotation format',
		'MGF',
		'OME-TIFF',
		'COMBINE OMEX',
		'pair',
		'GROMACS itp',
		'strider format',
		'GTF',
		'idXML',
		'nrrd',
		'featureXML',
		'SNP',
		'PSL',
		'raw',
		'IDAT',
		'PDB database entry format',
		'TIDE TXT',
		'AVI',
		'UniProtKB format',
		'PDF',
		'FASTA-aln',
		'OWL format',
		'Annotated text format',
		'JASPAR format',
		'ig',
		'EMBL format',
		'ACE',
		'protein',
		'DICOM format',
		'XML',
		'dna',
		'Trajectory format (binary)',
		'Nexus format',
		'msh',
		'PHD',
		'qualsolid',
		'Map format',
		'Zstandard format',
		'BinPos',
		'pcx',
		'Pileup',
		'qualsolexa',
		'plain text format (unformatted)',
		'bigWig',
		'RNAML',
		'PHYLIP sequential',
		'GML',
		'giFASTA format',
		'mira',
		'newick',
		'LSM',
		'refseqp',
		'SDF',
		'Stockholm format',
		'dta',
		'codata',
		'Ensembl variation file format',
		'nii',
		'GenBank-like format (text)',
		'Phylogenetic tree report (tree distances) format',
		'meme-motif',
		'Sequence feature annotation format',
		'FASTQ-like format',
		'Format',
		'HMMER3',
		'PSF',
		'csfasta',
		'consensus',
		'pure protein',
		'OBO',
		'Phylogenetic tree format',
		'bedgraph',
		'docx',
		'InChIKey',
		'Gene annotation format',
		'Phylogenetic tree format (text)',
		'MaxQuant APL peaklist format',
		'Data index format',
		'Molfile',
		'InChI',
		'PS',
		'HMMER profile alignment (sequences versus HMMs)',
		'ASN.1 sequence format',
		'Sequence record format',
		'SPARQL',
		'Format (by type of data)',
		'UniProtKB XML',
		'3D-1D scoring matrix format',
		'SBGN-ML',
		'Microarray experiment data format',
		'nucleotide',
		'BCF',
	],
	y: [
		8, 3, 4, 301, 2, 2, 6, 79, 6, 43, 1, 6, 50, 18, 8, 31, 4, 4, 5, 44, 6, 11,
		15, 41, 9, 5, 1, 3, 3, 14, 1, 9, 4, 2, 3, 3, 3, 558, 23, 6, 12, 43, 22, 2,
		2, 2, 4, 2, 487, 18, 3, 8, 29, 309, 18, 8, 1, 21, 3, 2, 35, 5, 1, 6, 1, 13,
		23, 1, 14, 6, 38, 109, 17, 1, 55, 15, 5, 4, 78, 3, 2, 1, 2, 1, 655, 40, 1,
		2, 30, 1, 2, 4, 3, 9, 3, 48, 5, 5, 21, 6, 12, 4, 1, 34, 1, 34, 3, 3, 26, 1,
		23, 6, 52, 278, 2, 105, 12, 24, 31, 29, 10, 1, 1, 30, 5, 2, 17, 6, 9, 106,
		1, 538, 1, 35, 1, 1, 2, 2, 3, 6, 4, 315, 3, 5, 2, 3, 22, 10, 1, 27, 1, 6, 2,
		2277, 1, 52, 2, 2, 4, 67, 21, 8, 5, 1, 1, 2, 4, 7, 7, 84, 4, 3, 1, 7, 4, 14,
		1, 996, 4, 7, 2, 2, 14, 1, 14, 26, 225, 9, 33, 1, 30, 33, 9, 1, 22, 57, 12,
		11, 5, 1, 14, 3, 4, 11, 31, 2, 2, 2, 3, 210, 4, 7, 7, 2, 354, 6, 2, 84, 5,
		4, 2, 1, 4, 217, 53, 10, 44, 8, 16, 28, 12, 6, 5, 2, 18, 7, 10, 3, 2, 7, 17,
		35, 2, 16, 13, 154, 8, 1, 25, 2, 3, 2, 5, 1, 5, 2, 23, 5, 84, 59, 4, 1, 1,
		4, 3, 41, 2, 1, 96, 6, 37, 19, 7, 8, 7, 2, 7, 18, 19, 56, 8, 1, 3, 4, 5, 18,
		1, 26, 1, 3, 6, 2, 3, 7, 2, 16, 2, 1, 4, 19, 7, 10, 4, 1, 2, 5, 7, 28,
	],
};
