export const outputData = {
	x: [
		'K-mer countgraph',
		'BioPAX',
		'consensusXML',
		'SQLite format',
		'SFF',
		'sif',
		'Phylip format variant',
		'MAF',
		'trr',
		'GCG',
		'WIG',
		'qual',
		'X!Tandem XML',
		'genePred',
		'Sequence motif format',
		'GEN',
		'Mass spectrometry data format',
		'mzML',
		'Cytoscape input file format',
		'Image format',
		'BLAST XML v2 results format',
		'Sequence feature table format (text)',
		'Tertiary structure format',
		'GFF3',
		'dssp',
		'qual454',
		'mzData',
		'XMFA',
		'Sequence feature table format',
		'strider format',
		'GROMACS itp',
		'HET group dictionary entry format',
		'COMBINE OMEX',
		'nrrd',
		'idXML',
		'GTF',
		'VCF',
		'Sequence variation annotation format',
		'Pearson format',
		'pickle',
		'MGF',
		'customtrack',
		'Taxonomy',
		'OBO format',
		'dat',
		'MSF',
		'mzQuantML',
		'SAM',
		'EPS',
		'FASTA',
		'Protein interaction format',
		'TIFF',
		'BioYAML',
		'ZIP format',
		'Alignment format',
		'DSV',
		'JSON-LD',
		'proBED',
		'BioJSON (Jalview)',
		'TNG',
		'Matrix format',
		'SEQUEST .out file',
		'Mol2',
		'Biodiversity data format',
		'CHP',
		'SMILES',
		'N-Triples',
		'Hidden Markov model format',
		'HDF5',
		'GROMACS top',
		'bgzip',
		'Textual format',
		'Dot-bracket format',
		'SRA format',
		'SQL',
		'Format',
		'FASTQ-like format',
		'Protein secondary structure format',
		'HMMER3',
		'fitch program',
		'codata',
		'dta',
		'Sequence feature annotation format',
		'meme-motif',
		'nii',
		'bedgraph',
		'docx',
		'Phylogenetic tree format',
		'Protein report format',
		'csfasta',
		'OBO',
		'InChI',
		'Data index format',
		'KNIME datatable format',
		'PS',
		'SBGN-ML',
		'3D-1D scoring matrix format',
		'BCF',
		'Workflow format',
		'TAR format',
		'FASTG',
		'Microarray experiment data format',
		'Sequence record format',
		'ASN.1 sequence format',
		'Format (by type of data)',
		'N-Quads',
		'PDF',
		'UniProtKB format',
		'Sequence distance matrix format',
		'match',
		'FASTA-aln',
		'raw',
		'SNP',
		'featureXML',
		'TIDE TXT',
		'PSL',
		'PDB database entry format',
		'RNA secondary structure format',
		'XML',
		'dna',
		'DICOM format',
		'nexusnon',
		'Nexus format',
		'msh',
		'JASPAR format',
		'Annotated text format',
		'protein',
		'EMBL format',
		'ACE',
		'PHYLIP sequential',
		'bigWig',
		'GML',
		'ig',
		'RNAML',
		'DASGFF',
		'BinPos',
		'Map format',
		'qualsolexa',
		'Pileup',
		'plain text format (unformatted)',
		'MHTML',
		'MEME background Markov model',
		'Stockholm format',
		'SDF',
		'mirGFF3',
		'newick',
		'mira',
		'ClustalW format',
		'qcML',
		'pepXML',
		'bed12',
		'SED-ML',
		'PHYLIP format',
		'FASTQ',
		'Open Annotation format',
		'nbrf/pir',
		'RDF/XML',
		'GFA 2',
		'PSI MI TAB (MITAB)',
		'BMP',
		'BED',
		'Map',
		'GFA 1',
		'CSV',
		'Alignment format (text)',
		'markx0',
		'R file format',
		'Thermo RAW',
		'AMBER top',
		'ObjTables',
		'pkl',
		'Biological pathway or network report format',
		'SBML',
		'ISA-TAB',
		'GCT/Res format',
		'Article format',
		'SVG',
		'PDB',
		'AGP',
		'xpm',
		'Graph format',
		'JPG',
		'Biological pathway or network format',
		'Sequence range format',
		'Binary format',
		'phyloXML',
		'GIF',
		'mzIdentML',
		'OWL/XML',
		'FASTA search results format',
		'BLAST results',
		'Gene expression report format',
		'CopasiML',
		'afg',
		'mhd',
		'RDF format',
		'GenBank-HTML',
		'Protein structure report (quality evaluation) format',
		'nmrML',
		'Loom',
		'Sequence profile format',
		'netCDF',
		'MPEG-4',
		'mmCIF',
		'CHARMM rtf',
		'xls',
		'GCG MSF',
		'PNG',
		'ibd',
		'bigBed',
		'Phylip tree distance format',
		'MTX',
		'Turtle',
		'ARB',
		'XYZ',
		'GFF',
		'FASTQ-sanger',
		'TraML',
		'Sequence annotation track format',
		'MAGE-ML',
		'FASTA-like',
		'ABI',
		'Mascot .dat file',
		'NeXML',
		'JSON',
		'mzTab',
		'xlsx',
		'GenBank format',
		'CWL',
		'YAML',
		'Trajectory format',
		'imzML metadata file',
		'BAI',
		'XTC',
		'TSV',
		'PSI MI XML (MIF)',
		'Text',
		'Database hits (sequence) format',
		'GFF3-seq',
		'HTML',
		'mzXML',
		'Sequence assembly format',
		'protXML',
		'bed6',
		'BLAST XML results format',
		'Ontology format',
		'FASTQ-illumina',
		'nexus-seq',
		'PRIDE XML',
		'FASTA-like (text)',
		'BLC',
		'mdcrd',
		'CRAM',
		'scores format',
		'BAM',
		'Vienna local RNA secondary structure format',
		'Manchester OWL Syntax',
		'Phylip distance matrix',
		'GFF2',
		'FASTQ-like format (text)',
		'FASTA-HTML',
		'MAP',
	],
	y: [
		1, 5, 17, 20, 4, 11, 2, 10, 12, 4, 47, 8, 5, 1, 5, 2, 4, 62, 6, 473, 1, 16,
		8, 162, 2, 11, 2, 3, 5, 4, 8, 2, 3, 8, 59, 43, 216, 5, 4, 6, 33, 1, 3, 2,
		19, 1, 6, 106, 32, 746, 1, 44, 1, 1, 14, 10, 2, 6, 2, 4, 106, 1, 15, 8, 1,
		2, 6, 2, 6, 7, 1, 1060, 5, 1, 3, 29, 4, 1, 6, 4, 4, 15, 4, 8, 4, 27, 5, 6,
		11, 1, 1, 4, 1, 12, 7, 1, 3, 18, 21, 2, 2, 2, 2, 5, 10, 6, 467, 1, 1, 1, 13,
		17, 4, 22, 4, 2, 2, 1, 349, 1, 12, 1, 16, 1, 3, 3, 1, 15, 4, 2, 29, 19, 4,
		1, 1, 4, 10, 1, 10, 17, 9, 2, 10, 24, 2, 58, 2, 22, 10, 26, 3, 3, 22, 111,
		1, 6, 13, 1, 3, 12, 217, 1, 3, 406, 3, 1, 2, 2, 4, 2, 5, 9, 46, 2, 2, 1,
		133, 123, 6, 1, 33, 57, 13, 2, 92, 8, 19, 34, 2, 2, 11, 7, 3, 2, 4, 21, 2,
		1, 1, 7, 1, 16, 2, 7, 1, 34, 6, 363, 4, 3, 1, 8, 13, 1, 3, 112, 10, 9, 3, 1,
		4, 2, 4, 8, 307, 28, 80, 23, 1, 35, 2, 5, 27, 10, 615, 8, 47, 6, 2, 1054,
		19, 1, 9, 3, 3, 1, 2, 3, 4, 10, 2, 8, 5, 4, 231, 1, 2, 2, 2, 3, 7, 2,
	],
};
