name: Auto Add to Org Projects

on:
  issues:
    types:
      - opened
      - assigned
      - reopened
      - edited
      - deleted
      - labeled
      - unlabeled

permissions:
  issues: read

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add Issue to General Overview (Project 6)
        uses: actions/add-to-project@v2
        continue-on-error: true
        with:
          project-url: 'https://github.com/orgs/inab/projects/6'
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}

      - name: Add Issue to Specific Project Board
        uses: actions/add-to-project@v2
        continue-on-error: true
        with:
          project-url: 'https://github.com/orgs/inab/projects/3'
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
